local PetInventoryService = require(script.Parent.Pets.PetInventoryService)
local PetPartyService = require(script.Parent.Pets.PetPartyService)
local StudioPetPreview = require(script.Parent.Pets.StudioPetPreview)
local SlimeMovementService = require(script.Parent.Slimes.SlimeMovementService)
local CombatService = require(script.Parent.Combat.CombatService)

PetInventoryService.Start()
PetPartyService.Start(PetInventoryService)
StudioPetPreview.Start(PetPartyService, PetInventoryService)
SlimeMovementService.Start()
CombatService.Start()
print("[Pawlands] Pet, movement, slime AI, and player combat foundations ready.")

script.Destroying:Connect(function()
	CombatService.Stop()
	SlimeMovementService.Stop()
end)
