local PetInventoryService = require(script.Parent.Pets.PetInventoryService)
local PetPartyService = require(script.Parent.Pets.PetPartyService)
local PetCombatService = require(script.Parent.Pets.PetCombatService)
local PetCombatFeedbackService = require(script.Parent.Pets.PetCombatFeedbackService)
local PetVitalsService = require(script.Parent.Pets.PetVitalsService)
local StudioPetPreview = require(script.Parent.Pets.StudioPetPreview)
local SlimeMovementService = require(script.Parent.Slimes.SlimeMovementService)
local CombatService = require(script.Parent.Combat.CombatService)
local DialogueService = require(script.Parent.Dialogue.DialogueService)

PetInventoryService.Start()
PetPartyService.Start(PetInventoryService)
PetVitalsService.Start(PetInventoryService, PetPartyService)
PetCombatService.Start(PetPartyService, PetVitalsService)
PetCombatFeedbackService.Start()
StudioPetPreview.Start(PetPartyService, PetInventoryService, PetVitalsService, PetCombatFeedbackService)
SlimeMovementService.Start(PetCombatService, PetVitalsService, PetCombatFeedbackService)
CombatService.Start()
DialogueService.Start()
print("[Pawlands] Pet, combat, movement, slime AI, and dialogue foundations ready.")

script.Destroying:Connect(function()
	DialogueService.Stop()
	CombatService.Stop()
	SlimeMovementService.Stop()
	PetCombatFeedbackService.Stop()
	PetCombatService.Stop()
	PetVitalsService.Stop()
end)
