return table.freeze({
	RemoteFolderName = "Remotes",
	RemoteFunctionName = "PetInventory",

	GuiName = "Inventory",
	HudGuiName = "HUD",
	HudRootName = "Hud",
	HudLeftSideName = "LeftSide",
	HudRowName = "Row1",
	HudInventoryButtonName = "InventoryButton",
	HudKeyButtonName = "KeyButton",

	RuntimePetTilePrefix = "RuntimePet_",
	RuntimeEquippedPetTilePrefix = "RuntimeEquippedPet_",
	RuntimePartySlotPrefix = "RuntimePartySlot_",
	DefaultVariantName = "Normal",
	FavoriteOffText = "Favorite: OFF",
	FavoriteOnText = "Favorite: ON",
	FavoriteStrokeColor = Color3.fromRGB(255, 220, 64),
	PetCapacity = 400,
	ItemCapacity = 250,
	EquippedPetsTextFormat = "Equipped Pets (%d/%d)",
	CapacityCountTextFormat = "%d/%d",
	EmptyBadgeText = "0",
	EmptyPetsText = "No pets in this category!",
	EmptyItemsText = "No items in this category!",
	DamageTextFormat = "%d DMG",

	PartyMutationLockedAttributeName = "PawlandsPetPartyLocked",
	PartyMutationExitGraceSeconds = 1.75,
	PartyMutationPollIntervalSeconds = 0.10,
	PartyMutationLockedReason = "Pet party can't be changed during combat.",
	PartyMutationNotificationKey = "PetPartyCombatLock",
	PartyMutationNotificationDurationSeconds = 2.4,

	Actions = table.freeze({
		Snapshot = "Snapshot",
		ToggleEquip = "ToggleEquip",
		ToggleFavorite = "ToggleFavorite",
	}),
})
