-- Motion follows the formation / ground / flying approach in the UXR reference.
return table.freeze({
	VisualFolderName = "PawlandsPetVisuals",
	Spacing = 4.5,
	RowDepth = 4.5,
	FirstRow = 5,
	ModelPadding = 0.8,
	FollowSpeed = 8,
	TurnSpeed = 10,
	VerticalSpeed = 12,
	MoveThreshold = 0.65,
	WalkBlendSpeed = 8,
	HopHeight = 0.45,
	HopFrequency = 9,
	WalkLean = 0.10,
	IdleBob = 0.025,
	IdleFrequency = 3,
	FlyBob = 0.18,
	FlyFrequency = 4,
	FlyLean = -0.08,
	GroundClearance = 0.06,
	-- A small support area spans seams between wooden planks.
	GroundProbeWidth = 1.5,
	GroundProbeThickness = 0.1,
	RayHeight = 12,
	RayDistance = 60,
	MaxGroundDrop = 28,
	MinGroundNormalY = 0.3,
	TeleportDistance = 60,
	RecallDistance = 80,
	RenderDistance = 220,
	AssetRetrySeconds = 2,
})
