return table.freeze({
	StageAttributeName = "PawlandsTutorialStage",
	ProgressAttributeName = "PawlandsTutorialProgress",
	GoalAttributeName = "PawlandsTutorialGoal",
	CombatEligibleAttributeName = "PawlandsTutorialCombatEligible",
	InputModeAttributeName = "PawlandsTutorialInputMode",
	StarterPetHitConfirmedAttributeName = "PawlandsTutorialStarterPetHitConfirmed",

	Stages = table.freeze({
		NotStarted = "NotStarted",
		LearnMove = "LearnMove",
		LearnSprint = "LearnSprint",
		MeetAlex = "MeetAlex",
		GoToZone = "GoToZone",
		LearnAttack = "LearnAttack",
		InCombat = "InCombat",
		ReturnToAlex = "ReturnToAlex",
		SoloComplete = "SoloComplete",
		ChooseStarterPet = "ChooseStarterPet",
		EquipStarterPet = "EquipStarterPet",
		PetCombatReady = "PetCombatReady",
		LearnPetCombat = "LearnPetCombat",
		PetInCombat = "PetInCombat",
		Completed = "Completed",
	}),

	AcceptCombatAction = "AcceptTutorialCombat",
	CompleteSoloCombatAction = "CompleteSoloTutorialCombat",
	-- Kept as a compatibility alias for the previous 3A.2 action name.
	CompleteCombatAction = "CompleteTutorialCombat",
	BeginStarterPetChoiceAction = "BeginStarterPetChoice",

	RemoteFolderName = "Remotes",
	InputModeRemoteName = "TutorialInputMode",
	StarterPetChoiceRemoteName = "StarterPetChoice",

	StarterPetGrantedAttributeName = "PawlandsStarterPetGranted",
	StarterPetUidAttributeName = "PawlandsStarterPetUid",
	StarterPetSpeciesAttributeName = "PawlandsStarterPetSpecies",
	StarterPetChoices = table.freeze({
		Bunny = "BunnyCard",
		Cat = "CatCard",
		Dog = "DogCard",
	}),
	StarterPetSelectionGuiName = "StarterPetSelection",
	StarterPetSelectedStrokeColor = Color3.fromRGB(255, 215, 84),
	StarterPetStrokeTweenSeconds = 0.14,
	StarterPetRewardDelaySeconds = 0.9,
	StarterPetGrantNotificationSeconds = 3.8,
	InputModes = table.freeze({
		Keyboard = "Keyboard",
		Gamepad = "Gamepad",
		Touch = "Touch",
	}),

	ZoneCheckSeconds = 0.15,
	MoveLessonDistanceStuds = 7,
	SprintLessonMinSpeedStuds = 12.0,
	SprintLessonRequiredSeconds = 0.35,
	AttackLessonInitialSlimeCount = 1,
	SoloCombatSlimeCount = 3,
	PetCombatInitialSlimeCount = 1,
	PetCombatSlimeCount = 3,
	RequiredAttackActionType = "M1",
	CombatExitLeewayStuds = 8,
	CombatExitGraceSeconds = 0.60,
	CombatMissingCharacterGraceSeconds = 0.75,

	QuestGuiName = "QuestTracker",
	QuestTitle = "A New Adventure",
	MeetAlexPrefix = "Meet",
	MeetAlexItem = "Alex",
	GoToZonePrefix = "Go to",
	GoToZoneItem = "Training Area",
	CombatPrefix = "Defeat",
	CombatItem = "Training Slimes",
	ReturnPrefix = "Return to",
	ReturnItem = "Alex",
	EquipStarterPrefix = "Equip your first",
	EquipStarterItem = "Pet",

	Arrow = table.freeze({
		AssetRootName = "Assets",
		AssetTutorialFolderName = "Tutorial",
		AssetName = "ArrowModel",
		RuntimeName = "TutorialArrowModel_Client",

		WorldRootName = "StarterStoneIsland",
		NpcFolderName = "NPC",
		AlexName = "Alex",
		AlexTargetPartName = "HumanoidRootPart",
		TutorialWorldFolderName = "Tutorial",
		ZonesName = "Zones",
		CombatZoneName = "CombatZone",

		BackOffsetWhenMoving = 1.15,
		BackOffsetWhenIdle = 0.35,
		HeightAbovePlayer = 2.75,
		NearDistance = 8,
		TransitionDistance = 18,
		AboveTargetHeight = 4.15,
		ArrowScale = 1.12,
		SpawnTime = 0.35,
		DespawnTime = 0.25,
		MinAnimScale = 0.08,
		PositionLerpSpeed = 8.0,
		RotationLerpSpeed = 10.0,
		MoveDirectionLerpSpeed = 7.0,
		BobSpeed = 3.5,
		PlayerBobAmount = 0.10,
		TargetBobAmount = 0.18,
		TargetMissingGraceSeconds = 0.35,
		RotationOffset = Vector3.new(90, -90, 0),
	}),

	CompletionCelebration = table.freeze({
		GuiName = "TutorialComplete",
		MainName = "Main",
		TitleName = "Title",
		PopScaleName = "PopScale",
		LeftConfettiName = "LeftConfetti",
		RightConfettiName = "RightConfetti",
		SoundName = "CompleteSound",
		PiecePrefix = "Piece",

		DefaultDurationSeconds = 2.6,
		MinimumDurationSeconds = 3.05,
		TitlePopStartSeconds = 0.06,
		ConfettiBurstStartSeconds = 0.18,

		-- Burst #1 is deliberately short and punchy. Every authored piece is then
		-- hidden/reset to its corner origin before a wider, higher second launch.
		FirstWaveDelayScale = 0.80,
		FirstWaveDurationScale = 0.42,
		SecondWaveStartSeconds = 0.82,
		SecondWaveDelayScale = 0.55,
		SecondWaveDurationScale = 0.98,
		SecondWaveResetGapSeconds = 0.045,
		SecondWaveHorizontalPushMin = 0.52,
		SecondWaveHorizontalPushMax = 1.05,
		SecondWaveVerticalLiftMin = 0.34,
		SecondWaveVerticalLiftMax = 0.72,
		SecondWaveExtraRotation = 220,
		SecondWaveFadeFraction = 0.64,
		MinimumFadeSeconds = 0.18,

		IntroScale = 0.70,
		PopScale = 1.14,
		TitlePopSeconds = 0.20,
		TitleSettleSeconds = 0.15,
		SecondTitlePulseScale = 1.045,
		SecondTitlePulseSeconds = 0.10,
		SecondTitleSettleSeconds = 0.12,
	}),

	Cue = table.freeze({
		GuiName = "TutorialCues",
		SafeBoundsName = "SafeBounds",
		ClickTemplateName = "ClickTemplate",
		TapTemplateName = "TapTemplate",
		RuntimeName = "Runtime_AttackCue",
		EquipRuntimeName = "Runtime_EquipStarterCue",
		InitialDelaySeconds = 2.25,
		EquipStarterInitialDelaySeconds = 1.75,
		IntroScale = 0.80,
		PulseDownScale = 0.84,
		PulseUpScale = 1.08,
		IntroSeconds = 0.16,
		PressSeconds = 0.10,
		PopSeconds = 0.14,
		SettleSeconds = 0.12,
		FadeSeconds = 0.12,
		PulseRestSeconds = 0.55,
		RelocateHoldSeconds = 0.75,
	}),

	NotificationKey = "TutorialGuidance",
	MoveHintKeyboard = "MOVE: Use WASD to move",
	MoveHintGamepad = "MOVE: Use the Left Stick to move",
	MoveHintTouch = "MOVE: Use the joystick to move",
	SprintHintKeyboard = "SPRINT: Press Ctrl to toggle Sprint",
	SprintHintGamepad = "SPRINT: Press L3 to toggle Sprint",
	CombatHintKeyboard = "ATTACK: Click to attack the Slime",
	CombatHintGamepad = "ATTACK: Press RT to attack the Slime",
	CombatHintTouch = "ATTACK: Tap Attack to strike",
	PetCombatHint = "Pets attack nearby enemies automatically.",
})
