return table.freeze({
	StageAttributeName = "PawlandsTutorialStage",
	ProgressAttributeName = "PawlandsTutorialProgress",
	GoalAttributeName = "PawlandsTutorialGoal",
	CombatEligibleAttributeName = "PawlandsTutorialCombatEligible",
	InputModeAttributeName = "PawlandsTutorialInputMode",

	Stages = table.freeze({
		NotStarted = "NotStarted",
		LearnMove = "LearnMove",
		LearnSprint = "LearnSprint",
		MeetAlex = "MeetAlex",
		GoToZone = "GoToZone",
		LearnAttack = "LearnAttack",
		InCombat = "InCombat",
		ReturnToAlex = "ReturnToAlex",
		SoloComplete = "SoloComplete",
		ChooseStarterPet = "ChooseStarterPet",
		EquipStarterPet = "EquipStarterPet",
		PetCombatReady = "PetCombatReady",
		Completed = "Completed",
	}),

	AcceptCombatAction = "AcceptTutorialCombat",
	CompleteSoloCombatAction = "CompleteSoloTutorialCombat",
	-- Kept as a compatibility alias for the previous 3A.2 action name.
	CompleteCombatAction = "CompleteTutorialCombat",
	BeginStarterPetChoiceAction = "BeginStarterPetChoice",

	RemoteFolderName = "Remotes",
	InputModeRemoteName = "TutorialInputMode",
	StarterPetChoiceRemoteName = "StarterPetChoice",

	StarterPetGrantedAttributeName = "PawlandsStarterPetGranted",
	StarterPetUidAttributeName = "PawlandsStarterPetUid",
	StarterPetSpeciesAttributeName = "PawlandsStarterPetSpecies",
	StarterPetChoices = table.freeze({
		Bunny = "BunnyCard",
		Cat = "CatCard",
		Dog = "DogCard",
	}),
	StarterPetSelectionGuiName = "StarterPetSelection",
	StarterPetSelectedStrokeColor = Color3.fromRGB(255, 215, 84),
	StarterPetStrokeTweenSeconds = 0.14,
	StarterPetRewardDelaySeconds = 0.9,
	StarterPetGrantNotificationSeconds = 3.8,
	InputModes = table.freeze({
		Keyboard = "Keyboard",
		Gamepad = "Gamepad",
		Touch = "Touch",
	}),

	ZoneCheckSeconds = 0.15,
	MoveLessonDistanceStuds = 7,
	SprintLessonMinSpeedStuds = 12.0,
	SprintLessonRequiredSeconds = 0.35,
	AttackLessonInitialSlimeCount = 1,
	SoloCombatSlimeCount = 3,
	RequiredAttackActionType = "M1",
	CombatExitLeewayStuds = 8,
	CombatExitGraceSeconds = 0.60,
	CombatMissingCharacterGraceSeconds = 0.75,

	QuestGuiName = "QuestTracker",
	QuestTitle = "A New Adventure",
	MeetAlexPrefix = "Meet",
	MeetAlexItem = "Alex",
	GoToZonePrefix = "Go to",
	GoToZoneItem = "Training Area",
	CombatPrefix = "Defeat",
	CombatItem = "Training Slimes",
	ReturnPrefix = "Return to",
	ReturnItem = "Alex",
	EquipStarterPrefix = "Equip your first",
	EquipStarterItem = "Pet",

	Cue = table.freeze({
		GuiName = "TutorialCues",
		SafeBoundsName = "SafeBounds",
		ClickTemplateName = "ClickTemplate",
		TapTemplateName = "TapTemplate",
		RuntimeName = "Runtime_AttackCue",
		InitialDelaySeconds = 2.25,
		IntroScale = 0.80,
		PulseDownScale = 0.84,
		PulseUpScale = 1.08,
		IntroSeconds = 0.16,
		PressSeconds = 0.10,
		PopSeconds = 0.14,
		SettleSeconds = 0.12,
		FadeSeconds = 0.12,
		PulseRestSeconds = 0.55,
		RelocateHoldSeconds = 0.75,
	}),

	NotificationKey = "TutorialGuidance",
	MoveHintKeyboard = "MOVE: Use WASD to move",
	MoveHintGamepad = "MOVE: Use the Left Stick to move",
	MoveHintTouch = "MOVE: Use the joystick to move",
	SprintHintKeyboard = "SPRINT: Press Ctrl to toggle Sprint",
	SprintHintGamepad = "SPRINT: Press L3 to toggle Sprint",
	CombatHintKeyboard = "ATTACK: Click to attack the Slime",
	CombatHintGamepad = "ATTACK: Press RT to attack the Slime",
	CombatHintTouch = "ATTACK: Tap Attack to strike",
})
