local PetFollowController = require(script.Parent.Pets.PetFollowController)
local PetCombatFeedbackController = require(script.Parent.Pets.Combat.PetCombatFeedbackController)
local PetHealthbarController = require(script.Parent.Pets.Combat.PetHealthbarController)
local PlayerMovementController = require(script.Parent.Player.PlayerMovementController)
local PlayerCombatController = require(script.Parent.Combat.PlayerCombatController)
local PlayerHitReactionController = require(script.Parent.Combat.PlayerHitReactionController)
local SlimeHealthbarController = require(script.Parent.Slimes.SlimeHealthbarController)
local SlimeFeedbackController = require(script.Parent.Slimes.SlimeFeedbackController)
local DialogueController = require(script.Parent.Dialogue.DialogueController)
local TextNotificationController = require(script.Parent.Notifications.TextNotificationController)
local TutorialCueController = require(script.Parent.Tutorial.TutorialCueController)
local TutorialController = require(script.Parent.Tutorial.TutorialController)
local StarterPetSelectionController = require(script.Parent.Tutorial.StarterPetSelectionController)

PetFollowController.Start()
PetCombatFeedbackController.Start()
PetHealthbarController.Start()
PlayerMovementController.Start()
PlayerCombatController.Start()
PlayerHitReactionController.Start()
SlimeHealthbarController.Start()
SlimeFeedbackController.Start()
DialogueController.Start()
TextNotificationController.Start()
StarterPetSelectionController.Start()
TutorialCueController.Start()
TutorialController.Start()

script.Destroying:Connect(function()
	TutorialController.Stop()
	TutorialCueController.Stop()
	StarterPetSelectionController.Stop()
	TextNotificationController.Stop()
	DialogueController.Stop()
	PetHealthbarController.Stop()
	SlimeFeedbackController.Stop()
	SlimeHealthbarController.Stop()
	PlayerHitReactionController.Stop()
	PlayerCombatController.Stop()
	PlayerMovementController.Stop()
	PetCombatFeedbackController.Stop()
	PetFollowController.Stop()
end)
